Rehab/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('api-auth',include("rest_framework.urls")),
    path('admin/', admin.site.urls),
    path('',TemplateView.as_view(template_name='index.html')),
    path('api/',include('api.urls')),
]

api/urls.py
from django.urls import path

from . import views

app_name="api"
urlpatterns=[
    path('', views.PatientView.as_view(),name="patient_list"),
    path("patient/create", views.PatientCreateView.as_view(), name="patient_create" ),
    path("doctor/<int:pk>", views.DoctorDetailView.as_view(), name="doctor_detail" ),
    path("patient/<int:pk>", views.PatientDetailView.as_view(), name="patient_detail" ),
    path("patient/<int:pk>/edit", views.PatientUpdateView.as_view(), name="patient_update" ),
    path("patient/<int:pk>/delete", views.PatientDeleteView.as_view(), name="patient_delete" ),
    path("patient/<int:pk>/mark", views.PatientMark.as_view(), name="patient_mark" ),
    path("hosp/<int:pk>/", views.HospitalSearch.as_view(), name="hospital_search" ),
    path("hosp_patient/<str:hosp_id>/", views.PatientsUnderHospital.as_view(), name="hosp_patient" ),
]

api/models.py
from datetime import datetime, date

from django.forms import forms
from django.utils import timezone
from django.db import models
from phone_field import PhoneField

# Create your models here.

class Hospital(models.Model):
    name=models.CharField(max_length=40, unique=True)
    address=models.CharField(max_length=100)
    zipcode=models.CharField(max_length=6)
    mobile=PhoneField(help_text='Contact phone number')
    email = models.EmailField(max_length=254)
    
    # For displaying hosp name in admin pannel instead of  Hospital object 1
    def __str__(self):
        return self.name

class Doctor(models.Model):
    doctor_name=models.CharField(max_length=30)
    created_on=models.DateTimeField("Date Registered", default=timezone.now)
    hospital=models.ForeignKey(Hospital, on_delete=models.CASCADE)
    specialization=models.CharField(max_length=70)
    email=models.EmailField(max_length = 254)
    mobile = PhoneField(help_text='Contact phone number')
    dob=models.DateField(default=date.today ,max_length=8)

    # For displaying doctor name in admin pannel instead of  Doctor object 1
    def __str__(self):
        return "Doctor %s " % (self.doctor_name)

appointment_time_choices = (
    ("10 am", "10 am"),
    ("11 am", "11 am"),
    ("12 pm", "12 pm"),
    ("1 pm", "1 pm"),
    ("2 pm", "2 pm"),
    ("3 pm", "3 pm"),
    ("4 pm", "4 pm"),
)
class Patient(models.Model):
    patient_name=models.CharField(max_length=30)
    hospital=models.ForeignKey(Hospital, on_delete=models.CASCADE)
    email=models.EmailField(max_length = 254)
    mobile = PhoneField(help_text='Contact phone number')
    dob=models.DateField(default=timezone.now,max_length=8)
    appointment_date=models.DateField(default=date.today ,max_length=8)
    appointment_time=models.CharField(choices=appointment_time_choices, default='10 am', max_length=10)
    created_on=models.DateTimeField(default=timezone.now)
    waiting_status=models.BooleanField(default=True)

    def __str__(self):
        return self.patient_name

    def clean_date(self):
        date = self.cleaned_data['appointment_date']
        if date < datetime.date.today():
            raise forms.ValidationError("The date cannot be in the past!")
        return date

    @property
    def is_waiting(self):
        return bool(self.waiting_status)

class Patient_Feedback(models.Model):
    patient_name=models.CharField(max_length=30)
    state=models.CharField(max_length=30)
    email=models.EmailField(max_length = 254)
    mobile = PhoneField(help_text='Contact phone number')
    hospital=models.ForeignKey(Hospital, on_delete=models.CASCADE)
    feedback=models.TextField(max_length=500)
    created_on=models.DateTimeField(default=timezone.now)

    # def __str__(self):
    #     return  (self.patient_name)% "%s's Feedback"

api/views.py
from django.core.mail import send_mail, EmailMultiAlternatives
from django.shortcuts import render, redirect

# Create your views here.
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.utils.html import strip_tags
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework.decorators import api_view

from Rehab.settings import EMAIL_HOST_USER
from api.serializers import *
from api.models import *
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView

# class IndexView(ListView):
#
#     def get_queryset(self):
#         return Patient.objects.filter(waiting_status=True)

# class PatientVieww(ListAPIView):
#     queryset=Patient.objects.all()
#     serializer_class=PatientSerializer

# above code or below code for view as json
class PatientView(APIView): # for displaying api response in browser as api or as webpage
    def get(self, request, *args, **kwargs):
        patients=Patient.objects.filter(waiting_status=True)
        serializer=PatientSerializer(patients,  many=True)
        #return Response(serializer.data) # api view
        return render(request, 'patient_list.html',{'patient_list':patients}) # as webpage view

class PatientCreateView(CreateView):
    model=Patient
    fields=['patient_name','hospital','email','mobile','dob','appointment_date','appointment_time']
    template_name='patient_create_form.html'
    success_url =  reverse_lazy("api:patient_list") 

# class PatientDetailView(APIView): # api view
#     def get(self, request, *args, **kwargs):
#         try:
#             id_ = self.kwargs.get("pk")
#             patients = Patient.objects.get(pk=id_)
#             serializer = PatientSerializer(patients)
#             return Response(serializer.data)  # else disp api view
#         except: # if no data found throw not found
#             return Response({'error':True, 'message':'Data not found'})



class PatientDetailView(DetailView): # for displaying api response in browser as webpage
    template_name = "patient_detail.html"
    fields = ['patient_name','hospital','email','mobile','dob','appointment_date','appointment_time', 'created_on', 'waiting_status']
    model=Patient


class PatientUpdateView(UpdateView):
    model=Patient
    fields = ['patient_name','hospital','email','mobile','dob']
    template_name = 'patient_update_form.html'
    success_url = reverse_lazy("api:patient_list")

class PatientDeleteView(DeleteView):
    model=Patient
    template_name = 'patient_confirm_delete.html'
    success_url = reverse_lazy("api:patient_list")

class PatientMark(APIView):
    success_url = reverse_lazy("api:patient_list")
    def get(self, request, *args, **kwargs):
        id_ = self.kwargs.get("pk")
        patient=Patient.objects.get(pk=id_)
        patient.waiting_status=False
        patient.save()
        recepient=str(patient.email)
        html_content=render_to_string('email_template.html',{'patient':patient})
        text_content=strip_tags(html_content)
        email=EmailMultiAlternatives(
            'Appointment confirmed',  #subject
            text_content,    #body
            EMAIL_HOST_USER, #from
            [recepient],
        )
        email.attach_alternative(html_content,"text/html")
        email.send()
        return redirect('api:patient_list')

class DoctorDetailView(APIView): # api view
    def get(self, request, *args, **kwargs):
        try:
            id_ = self.kwargs.get("pk")
            doctor = Doctor.objects.get(pk=id_)
            serializer = DoctorSerializer(doctor)
            return Response(serializer.data)  # else disp api view
        except: # if no data found throw not found
            return Response({'error':True, 'message':'Data not found'})

class HospitalSearch(APIView): # for displaying api response in browser as api or as webpage
    def get(self, request, *args, **kwargs):
        try:
            zipcode_ = self.kwargs.get("pk")
            hospital = Hospital.objects.filter(zipcode=zipcode_ )
            serializer = HospitalSerializer(hospital, many=True)
            # new_serializer={'error':False, 'message':'Data found'} # to add error false to serializer data
            # new_serializer=serializer.data     # we need to copy it to new dict  (serializer.data is a property of the class and therefore immutable)
            if Hospital.objects.filter(zipcode=zipcode_ ).exists():
                return Response(serializer.data)  # api view
            else:
                return Response({'error': True, 'message': 'No Clinic found at this Zip code'})
        except:
            return Response({'error':True, 'message':'No Clinic found at this Zip code'})

# @api_view(['GET'])
# def PatientsUnderHospital(request, name): # api view
#
#     #try:
#     hosp_patients = Patient.objects.filter(hospital=name)
#     serializer = PatientSerializer(hosp_patients,many=True)
#     return Response(serializer.data)
#         #return render(request, 'test.html',{'hosps':hosp_patients}) # as webpage view
#     #except: # if no data found throw not found
#         #return Response({'error':True, 'message':'Data not found'})

class PatientsUnderHospital(APIView): # for displaying api response in browser as api or as webpage
    def get(self, request, *args, **kwargs):
        try:
            hosp_id = self.kwargs.get("hosp_id")
            hosp_patients = Patient.objects.filter(hospital=hosp_id)  # as foreignkey stores id value instead of  name in model (hospital=2, patient_name=sangaram)
            serializer = PatientSerializer(hosp_patients, many=True)
            if Patient.objects.filter(hospital=hosp_id).exists():
                return Response(serializer.data)  # api view
            else:
                return Response({'error': True, 'message': 'No Patients  found under this Hosp'})
        except:
            return Response({'error':True, 'message':'No Patients  found under this Hosp'})

api/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Doctor Appointment</title>
    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
</head>
<body>
<nav class="navbar navbar-light bg-light">
    <a class="navbar-brand" href="http://127.0.0.1:8000/">
        Home
    </a>
</nav>
{% block content %}

{% endblock %}
</body>
</html>

api/templates/email_template.html
<!DOCTYPE html>
<html lang="en">
<body>
<h3>Dear {{patient.patient_name}}</h3><br>
Your Physiotherapy appointment at <b>{{patient.hospital}}</b> on <b>{{patient.appointment_date}} {{patient.appointment_time}}</b> is confirmed.<br>
Your medical well being is important to us. Please visit our website for further queries.<br>
We hope to see you soon.<br><br><br>
Sincerely,<br>
The Staff and Physiotherapist at<br>
{{patient.hospital}}
</body>
</html>

api/templates/patient_confirm_delete.html
{% extends 'base.html' %}
{% block content %}

<div class="container-fluid">

<form method="post">{% csrf_token %}
    <div class="row">
    <div class="col-md-1 col-xs-1 col-sm-1"></div>
            <div class="col-md-7 col-xs-7 col-sm-7">
    <p>Are you sure you want to delete "{{ object }}"?</p>
                  </div>
    </div>
    <input type="submit" value="Confirm" class="btn btn-danger" align="center">
</form>

</div>
{% endblock %}

api/templates/patient_create_form.html
{% extends 'base.html' %}
{% block content %}

<div class="container-fluid">

<form method="post">{% csrf_token %}
    <div class="row">
    <div class="col-md-1 col-xs-1 col-sm-1"></div>
            <div class="col-md-7 col-xs-7 col-sm-7">
    {{ form.as_p }}
            </div>
    </div>
    <input type="submit" value="Save" class="btn btn-success" align="center">
</form>

</div>
{% endblock %}

api/templates/patient_detail.html
{% extends 'base.html' %}
{% block content %}


<div class="container">
    <h1><centre>Patient Detail</centre></h1><br>
    <div class="panel panel-default">


 	<div class="panel panel-body">

 	<table class="table table-stripped">
 	<tr>
        <td><strong>Patient Name</strong></td>
        <td>{{ patient.patient_name }}</td>
    </tr>
        <tr>
        <td><strong>DOB</strong></td>
        <td>{{ patient.dob }}</td>
    </tr>
        <tr>
        <td><strong>Email</strong></td>
        <td>{{ patient.email }}</td>
    </tr>
        <tr>
        <td><strong>Mobile</strong></td>
        <td>{{ patient.mobile }}</td>
    </tr>
        <tr>
        <td><strong>Hospital Name</strong></td>
        <td>{{ patient.hospital }}</td>
    </tr>
    <tr>
        <td><strong>Created on</strong></td>
        <td>{{ patient.created_on }}</td>
    </tr>
    <tr>
        <td><strong>Appointment Date</strong></td>
        <td>{{ patient.appointment_date }}</td>
    </tr>
        <tr>
        <td><strong>Appointment Time</strong></td>
        <td>{{ patient.appointment_time }}</td>
    </tr>
    <tr>
        <td><strong>Waiting Status</strong></td>
        <td>{{ patient.waiting_status }}</td>

    </table>
    </div>
</div>

{{ patient.patient_name }}<br> <!-- can use object or patient both will work -->
{{ object.doctor }}<br>
{{ object.created_on }}<br>
{{ object.waiting_status }}<br>

</div>
{% endblock %}

api/templates/patient_list.html
{% extends 'base.html' %}
{% block content %}

<div class="container-fluid">

    <div class="row">
        <div class="col-md-1 col-xs-1 col-sm-1"></div>
                <div class="col-md-10 col-xs-10 col-sm-10">
                <h3 class="round3" align="center">Patient Waiting List</h3>
                 </div>
    <div class="col-md-1 col-xs-1 col-sm-1"></div>
    </div>

    <div class="row">
        <div class="col-md-10 col-xs-10 col-sm-10"></div>
                <div class="col-md-2 col-xs-1 col-sm-1">
          <a href="{% url 'api:patient_create' %}">

          <button type="button" class="btn btn-primary">
              <span class="glyphicon glyphicon-plus"></span>
          </button>
          </a><br>

        </div>
    </div>

    <br>
    {% csrf_token %}

    {% if patient_list %}
    {% for patient in patient_list %}
    <div class="row">
        <div class="col-md-1 col-xs-1 col-sm-1"></div>
            <div class="col-md-7 col-xs-7 col-sm-7">
                <ul class="list-group">
                    <li class="list-group-item">
                        <h3>
                            <a href="">
                                {{ patient.patient_name }}
                            </a>
                        </h3>
                        <br>
                        Mobile no: {{patient.mobile}}
                        <br>
                        Email: {{patient.email}}
                        <br>
                        Created on: {{ patient.created_on }}
                        <div>
                        <b>Hospital : {{ patient.hospital }}</b><br>
                        <b>Appointment on : {{patient.appointment_date}} -- {{patient.appointment_time}}</b>
                        </div>
                    </li>
                </ul><br>

        </div>

        <div class="col-md-1 col-xs-1 col-sm-1">

            <a href="{% url 'api:patient_mark' patient.id %}">
                <button type="button" class="btn btn-success">
                     <span class="glyphicon glyphicon-check"></span>
                </button>
            </a>
        </div>

        <div class="col-md-1 col-xs-1 col-sm-1">
            <a href="{% url 'api:patient_update' patient.id %}">
                <button type="button" class="btn btn-info">
                     <span class="glyphicon glyphicon-pencil"></span>
                </button>
            </a>
        </div>

        <div class="col-md-1 col-xs-1 col-sm-1">
            <a href="{% url 'api:patient_delete' patient.pk %}">
                <button type="button" class="btn btn-danger">
                     <span class="glyphicon glyphicon-trash"></span>
                </button>
            </a>
        </div>

</div>
    {% endfor %}
    {% endif %}

{% endblock %}

api/templates/patient_update_form.html
{% extends 'base.html' %}
{% block content %}

<div class="container-fluid">
<centre><h2>Patient Detail Edit form</h2></centre>
<br>
<form method="post">{% csrf_token %}
    <div class="row">
    <div class="col-md-1 col-xs-1 col-sm-1"></div>
            <div class="col-md-7 col-xs-7 col-sm-7">
    {{ form.as_p }}
            </div>
    </div>
    <input type="submit" value="Update" class="btn btn-success" align="center">
</form>

</div>
{% endblock %}

api/templates/test.html
{% extends 'base.html' %}
{% block content %}

<div class="container-fluid">

    <div class="row">
        <div class="col-md-1 col-xs-1 col-sm-1"></div>
                <div class="col-md-10 col-xs-10 col-sm-10">
                <h3 class="round3" align="center">Doctor List</h3>
                 </div>
    <div class="col-md-1 col-xs-1 col-sm-1"></div>
    </div>

    <div class="row">
        <div class="col-md-10 col-xs-10 col-sm-10"></div>
                <div class="col-md-2 col-xs-1 col-sm-1">
          <a href="{% url 'api:patient_create' %}">

          <button type="button" class="btn btn-primary">
              <span class="glyphicon glyphicon-plus"></span>
          </button>
          </a><br>

        </div>
    </div>

    <br>
    {% csrf_token %}

    {% if hosps %}
    {% for hosp in hosps %}
        
    <div class="row">
        <div class="col-md-1 col-xs-1 col-sm-1"></div>
            <div class="col-md-7 col-xs-7 col-sm-7">
                <ul class="list-group">
                    <li class="list-group-item">
                        <h1>
                         Patient  Name:   {{hosp.name}}
                        </h1>
                        <h3>
                            <a href="">
                              Patient name:  {{ hosp.patient_name }}
                            </a>
                        </h3>
                        <br>
                        {{ hosp.email }}
                        <br>
                        {{ hosp.created_on }}
                        <div>
                            Hospital : {{ hosp.hospital }}
                        </div>
                    </li>
                </ul><br>

        </div>


</div>
        
    {% endfor %}
    {% endif %}

{% endblock %}